### ISSUE TITLE
Are tests currently disabled because of #+ignore?

### ISSUE THREAD

**Issue by jgarte** [Lisp-Stat/lisp-stat#22]
Hi, are tests currently disabled because of this line?

https://github.com/Lisp-Stat/lisp-stat/blob/master/lisp-stat.asd#L39

**Comment by Symbolics** [comment]
Yes.  Prior to to introduction of the new systems, like `distributions` and `statistics`, a few temporary systems were here.  Now, Lisp-Stat is primarily a name space that brings selected functions into `LS-USER`. One example of this is `mean`, a wheel that's been reinvented in many individual statistical systems in the ecosystem.

So, in short, there's nothing to test in the LISP-STAT system itself; all the functionality is in the dependent systems.  I suppose someday it may make sense to have all of the dependent systems called from LISP-STAT, which is why the `ignore` is there rather than deleting it.
